### ISSUE TITLE
Really awesome fork!

### ISSUE THREAD

**Issue by Eviepayne** [Voldrix/onlyfans-dl-2#1]
I love this. Just saw your update on the original.
I'd recommend merging what I did in my repo with config.json.
Here's the [commit](https://github.com/k0rnh0li0/onlyfans-dl/pull/62/commits/fef43790c480e74b728965632d62b0850b59da68)

**Comment by Voldrix** [comment]
Thanks, I'm glad you like it. Separating the configuration out is probably a good idea, I just liked the idea of having a single file. I'll move them out next time I need to make a change.

**Comment by karlochacon** [comment]
loving right now I have some galleries I can share BTW just write I love this script to download content
