### ISSUE TITLE
Script no longer working for me.

### ISSUE THREAD

**Issue by kirbyjohnson** [Voldrix/onlyfans-dl-2#102]
I made sure to plug in the correct information for the variables as described in the readme but I still can't use the script. I get the following error message:
[command entered] - C:...Downloads\onlyfans-dl-2-master>onlyfans-dl.py belledelphine 

[output] - 
```
Usage: C:...Downloads\onlyfans-dl-2-master\onlyfans-dl.py <list of profiles / all> [optional: only get last <integer> days of posts]

Make sure to update the session variables at the top of this script (See readme).

Update Browser User Agent (Every time it updates): https://ipchicken.com/
```

I run the script through w10 on cmd
I made sure to run the command as instructed with the script name and then the only argument being the username of the onlyfans user. I even ran it with "all" just to see what would happen
C:...\onlyfans-dl-2-master> onlyfans-dl.py user
I ran the script with a bunch of different variations to see if it would help.:

onlyfans-dl.py "user"
onlyfans-dl.py <user>
onlyfans-dl.py 'user'
onlyfans-dl.py all
onlyfans-dl.py all 2
onlyfans-dl.py @user

**Comment by kirbyjohnson** [comment]
Nvm I fixed it. apparently with updated versions of python, I have to type in "python" before the script name. Please don't close this ticket until I can confirm it is working. The script is no longer giving me that error, but isn't showing progress for downloading media.
to be clear this command is giving me the error shown above:
onlyfans-dl.py user
and this command is stuck on "Downloading content to user folder":
python onlyfans-dl.py user

**Comment by kirbyjohnson** [comment]
EDIT: The script seems to be working now. I have a folder for the user and photos are being downloaded.

**Comment by svxnsvxnsvxn** [comment]
I cant even get it to run in cmd on Win11. It always closes itself right after opening. 
I tried it in PyCharm but then I have the same Problem as you mentioned:

```
Usage: C:...Downloads\onlyfans-dl-2-master\onlyfans-dl.py <list of profiles / all> [optional: only get last <integer> days of posts]

Make sure to update the session variables at the top of this script (See readme).

Update Browser User Agent (Every time it updates): https://ipchicken.com/
```
