### ISSUE TITLE
Header generation not working

### ISSUE THREAD

**Issue by vrstrabo** [Voldrix/onlyfans-dl-2#105]
Hi, actually I'm using your script for the as base for the auth system. A couple of days ago, before this message it was working, but now I think they introduced some new parameter to be added to header to make it work. Can you help me to fix it?

**Comment by vrstrabo** [comment]
Or actually can you fix your script?

**Comment by Voldrix** [comment]
The script is working fine for me. What is your actual problem?

**Comment by vrstrabo** [comment]
And I thought it was a problem, related to some missing parameters since I discovered they updated the parameter for the Sign generation
