### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by razzm8** [Voldrix/onlyfans-dl-2#109]
ran the script yesterday with no issues and no changes, went to run it today and im given this error

SUBSCRIPTIONS ERROR: http 400
Traceback (most recent call last):
  File "/Users/*myusername*/Documents/DL/dl2.py", line 272, in <module>
    for PROFILE in PROFILE_LIST:
TypeError: 'NoneType' object is not iterable

is this something to do with an update on the server side? as I said, made no changes since last running the script 

(script is up to date with all changes)

[
<img width="1182" alt="Screenshot 2023-12-26 at 9 01 34 pm" src="https://github.com/Voldrix/onlyfans-dl-2/assets/89358163/4b4a98d9-85d1-4d52-a85d-3bb2213f667c">
](url)

**Comment by Houkannis** [comment]
Same. Script worked fine yesterday and now suddenly giving http 400 error. Must be server side (?)

**Comment by Bmarquez1997** [comment]
Same here.  It seems to be an issue with the get_subscriptions() API call, it's returning a 400 status

**Comment by Voldrix** [comment]
OF changed their signature definitions again. The maintainer of those definitions updated them in a different repo, and not in their own for some reason. I switched the script to use the most up-to-date repo, which it used before, until it had fallen behind the other repo. So hopefully it doesn't move back and forth anymore.

Update the script or just change the link on line 274 from commit https://github.com/Voldrix/onlyfans-dl-2/commit/2c1f56fbd829fb072fc1527ef3d9d12c6eddf452
