### ISSUE TITLE
[max age] - Optional: Only get posts from the last <integer> days (Messages/Paid not affected)

### ISSUE THREAD

**Issue by karlochacon** [Voldrix/onlyfans-dl-2#11]
hi I was trying to workaround the issue with this profile

So I was trying to get only the last posts but I don't see it working even when 1 o more days

 .\onlyfans-dl-4.py Secretgirl1 [1]

I still see is getting all files like not age is specified

PS D:\OO> .\onlyfans-dl-4.py Secretgirl1 [30]

Downloading content to Secretgirl1
Found 535 posts
Secretgirl1/photos/2019-04-19_3983992/2019-04-19_28903577.jpeg
Secretgirl1/photos/2019-04-19_3983992/2019-04-19_28903585.jpeg
Secretgirl1/photos/2019-04-19_3983992/2019-04-19_28903589.jpeg
Secretgirl1/photos/2019-04-19_3983992/2019-04-19_28903599.jpeg

any idea

thanks

**Comment by Voldrix** [comment]
"[1]" is not an integer. Try just 1. I used square brackets in the documentation as opposed to angle brackets to indicate an optional parameter instead of a necessary parameter.

**Comment by karlochacon** [comment]
it does not take just the number

**PS D:\OO> .\onlyfans-dl-4.py Secretgirl1 30**
Traceback (most recent call last):
  File "D:\OO\onlyfans-dl-4.py", line 209, in <module>
    MAX_AGE = int((datetime.today() - timedelta(int(PROFILE_LIST.pop(-1)))).strftime("%s"))
ValueError: Invalid format string


**PS D:\OO> .\onlyfans-dl-4.py Secretgirl1 "30"**
Traceback (most recent call last):
  File "D:\OO\onlyfans-dl-4.py", line 209, in <module>
    MAX_AGE = int((datetime.today() - timedelta(int(PROFILE_LIST.pop(-1)))).strftime("%s"))
ValueError: Invalid format string


**PS D:\OO> .\onlyfans-dl-4.py Secretgirl1 '30'**
Traceback (most recent call last):
  File "D:\OO\onlyfans-dl-4.py", line 209, in <module>
    MAX_AGE = int((datetime.today() - timedelta(int(PROFILE_LIST.pop(-1)))).strftime("%s"))
ValueError: Invalid format string

**Comment by Voldrix** [comment]
I can't reproduce this on Linux, I'll get Python set up on Windows tomorrow and do some testing. I'm running Python3.9, but just tested on 3.8 and is still working. What version are you using? I'll try to replicate your environment.

Your error says it's on line 209, but in the file it's line 219. Maybe is just wonky Python counting, but make sure you're on the latest commit just so I'm testing with the same code as you.

**Comment by karlochacon** [comment]
great thanks a lot, now your questions

**PS D:\OO> python --version**
Python 3.9.5

**with lastest version** 
PS D:\OO> .\onlyfans-dl-5.py Secretgirl1 1
Traceback (most recent call last):
  File "D:\OO\onlyfans-dl-5.py", line 219, in <module>
    MAX_AGE = int((datetime.today() - timedelta(int(PROFILE_LIST.pop(-1)))).strftime("%s"))
ValueError: Invalid format string
PS D:\OO>

**Comment by karlochacon** [comment]
I think you can forget it I see I did not have the latest the one that skips the media with errors from OF

PS D:\OO> .\onlyfans-dl-5.py Secretgirl1

Secretgirl1 exists.
Downloading new media, skipping pre-existing.
Found 535 posts
Error getting: https://ca.convert.onlyfans.com/upload/9977bde30bd1886f13389e59ec2bcb06402235.jpeg (skipping)
Error getting: https://ca.convert.onlyfans.com/upload/5424582540f0ddaa238a1a99182e7d93915368.jpeg (skipping)
Error getting: https://ca.convert.onlyfans.com/upload/9977bde30bd1886f13389e59ec2bcb06572402.jpeg (skipping)
Error getting: https://ca.convert.onlyfans.com/upload/5424582540f0ddaa238a1a99182e7d93852723.jpeg (skipping)
Error getting: https://ca.convert.onlyfans.com/upload/9977bde30bd1886f13389e59ec2bcb06658401.jpeg (skipping)
Error getting: https://ca.convert.onlyfans.com/upload/9977bde30bd1886f13389e59ec2bcb06689071.jpeg (skipping)
Error getting: https://ca.convert.onlyfans.com/upload/5424582540f0ddaa238a1a99182e7d93830693.jpeg (skipping)
Error getting: https://ca.convert.onlyfans.com/upload/5424582540f0ddaa238a1a99182e7d93587417.jpeg (skipping)
Error getting: https://ca.convert.onlyfans.com/upload/5424582540f0ddaa238a1a99182e7d93829347.jpeg (skipping)
Error getting: https://ca.convert.onlyfans.com/upload/5424582540f0ddaa238a1a99182e7d93257307.jpeg (skipping)
Error getting: https://ca.convert.onlyfans.com/upload/5424582540f0ddaa238a1a99182e7d93277556.jpeg (skipping)
Error getting: https://ca.convert.onlyfans.com/upload/b4bab5089ddc66b26cf4934a318e01f2118479.jpeg (skipping)
Error getting: https://ca.convert.onlyfans.com/upload/b4bab5089ddc66b26cf4934a318e01f2333935.jpeg (skipping)
Error getting: https://ca.convert.onlyfans.com/upload/5424582540f0ddaa238a1a99182e7d93282921.jpeg (skipping)
