### ISSUE TITLE
USER_ID auth failed once again

### ISSUE THREAD

**Issue by safemuffins** [Voldrix/onlyfans-dl-2#110]
> USER_ID auth failed
> http 400
> 
> Update your browser user-agent variable, then sign back in to OF and update your session variables.
> https://ipchicken.com/

I have tried entering and re-entering USER_ID, USER_AGENT, X_BC, and SESS_COOKIE multiple times. I have even logged out, cleared onlyfans.com cookies and LocalStorage, multiple times, which generate new X_BC and SESS_COOKIE values every time. Consantly getting the error above now.

**Comment by Voldrix** [comment]
Dup #109
