### ISSUE TITLE
Lockout

### ISSUE THREAD

**Issue by SirKnotCLT** [Voldrix/onlyfans-dl-2#12]
USER_ID auth failed, trying without it...
(if this persists you can comment out the USER_ID variable)
Traceback (most recent call last):
  File "./onlyfans-dl.py", line 226, in <module>
    PROFILE_ID = str(get_user_info(PROFILE)["id"])
  File "./onlyfans-dl.py", line 113, in get_user_info
    info = api_request("/users/" + profile, 'user-info').json()
AttributeError: 'dict' object has no attribute 'json'

Was scraping fine earlier this morning, had no issues, but then suddenly python stopped working.  No matter what I did (tried across multiple machines) could not make the python package perform again.  Tried other python packages as well, still same result.  Tried clearing cache/securing new credentials, same outcome.  Looks like they are blocking this activity at an account level somehow?

**Comment by Voldrix** [comment]
The signing definitions changed, we're all temporarily locked out. The script pulls them dynamically from DIGITALCRIMINAL, so once they're fixed you won't need to do anything. Although I do recommend keeping up-to-date with the latest commit, as I've been making frequent bug fixes lately.
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1202

**Comment by Voldrix** [comment]
Fixed. Until next time it changes...
