### ISSUE TITLE
Dynamic rules have changed, so script fails

### ISSUE THREAD

**Issue by pawnstar81** [Voldrix/onlyfans-dl-2#124]
The dynamic rules have changed, so the script fails.

**Comment by rorgoroth** [comment]
The updated json repo is gone, so are any others that are up to date.

I have a feeling OF/GH are removing the repos for some bullshit excuse.

**Comment by Voldrix** [comment]
If anyone has a cached copy of the signature rules, I will find a reliable host for it.

**Comment by Voldrix** [comment]
Thanks for that @janolehuebner I added that statically to the file so we don't have to rely on remote hosting.
