### ISSUE TITLE
error 401

### ISSUE THREAD

**Issue by razzm8** [Voldrix/onlyfans-dl-2#125]
updated the script and had this error, also re-copied the main file to restart with all my relevant parameters and still getting this 

SUBSCRIPTIONS ERROR: http 401
Traceback (most recent call last):
  File "/Users/MYUSER/Documents/DL/dl3", line 288, in <module>
    for PROFILE in PROFILE_LIST:
TypeError: 'NoneType' object is not iterable

**Comment by Voldrix** [comment]
header signature repo changed, I added the definitions to the file statically. Try the latest patch.
