### ISSUE TITLE
I can't get it to work at all

### ISSUE THREAD

**Issue by Pwnager12345** [Voldrix/onlyfans-dl-2#22]
I have input all the variables correctly (I've checked multiple times) but when I try to run the command in Command Prompt, I get a momentary popup of a blank CMD window, then it closes and it prompts me for the next command. No error messages, no downloading messages. Nothing. 

I think I am having a similar issue to #3, What Escopy88 is describing is exactly what I am experiencing.

**Comment by Voldrix** [comment]
What's the exact command you're running?
