### ISSUE TITLE
Intermittent functioning of script - ERROR: Access denied

### ISSUE THREAD

**Issue by Stargatemunky** [Voldrix/onlyfans-dl-2#23]
I take it the API is still being messed with by OF, as 10% of the time I can get the script to work. The other 90% of the time the cookie session expires the instant I run the script and I have to manually re-edit the 'sess cookie' back into the .py and try again. Usually with no success.

Is this just because the script isn't updating enough to keep up? Or is there something more I could be doing?

cmd is usually of the form --> python ./onlyfans-dl.py *user* or python ./onlyfans-dl.py all

Usually I get an error saying "USER_ID auth failed, trying without it..."

No joy if I comment it out either :(

**Comment by Voldrix** [comment]
If it's logging you out when you run the script, then you need to update your browser's user agent in the script. Every time your browser updates.

**Comment by Stargatemunky** [comment]
I check that and change the cookie session each time, but the x-bc and user-id are the same each time.

It's just sometimes it works, most of the time it won't. And there's no real information to troubleshoot why :/

**Comment by Stargatemunky** [comment]
Seems to be working ok now, so I can only assume it's been updated behind the scenes.
