### ISSUE TITLE
No list of profiles when trying to load up 

### ISSUE THREAD

**Issue by anoeks** [Voldrix/onlyfans-dl-2#24]
Keep getting this when trying to load up the script, I've filled in user_id, user_agent, x_bc and sess cookie in the script file but getting same message.

F:\XXX\onlyfans-dl-2-master\onlyfans-dl-2-master>onlyfans-dl.py

Usage: F:\JXXX\onlyfans-dl-2-master\onlyfans-dl-2-master\onlyfans-dl.py <list of profiles / all> [optional: only get last <integer> days of posts]

Make sure to update the session variables at the top of this script
See readme for instructions
Update User Agent: https://ipchicken.com/

**Comment by Voldrix** [comment]
The first line it spits out tells you exactly how to use it, as does the readme. Add a profile name after the script
