### ISSUE TITLE
USER id failed error 

### ISSUE THREAD

**Issue by bnsave100** [Voldrix/onlyfans-dl-2#27]
it worked for couple of profiles but now stared showing this 
USER_ID auth failed, trying without it...
(if this persists you can comment out the USER_ID variable)

ERROR: Please refresh the page

**Comment by Voldrix** [comment]
Yea it's like that for everyone, the signing definitions must have changed again. Give digitalcriminal some time to reverse engineer it, and the script will start working again automatically, as it downloads that definition from him every time you run the script.

**Comment by bnsave100** [comment]
kk np I'll wait : )
