### ISSUE TITLE
Can't seem to get working

### ISSUE THREAD

**Issue by Escopy88** [Voldrix/onlyfans-dl-2#3]
Hello,

I followed all the instructions in the readme, got all the variables, user agent, userid, x_bc and sess from my current login session, but when I run the program it shuts down immediately. Is there something I'm missing?

**Comment by Voldrix** [comment]
Are you running on Python 3.9? If not, try updating and see if that works.

**Comment by Escopy88** [comment]
Thanks for the reply.

I was in fact running 3.8.5. Updated to 3.9.5 and seem to have the same issue. Black window pops up like it's starting, then immediately shuts down.

**Comment by Voldrix** [comment]
Are you running on Windows? TBH I'm not too familiar, but if you're running the script without any commandline parameters, it will just output instructions and then close. Try running it from powershell and you should see the instructions it spits out.

**Comment by Escopy88** [comment]
Yea i'm running it from powershell as administrator on windows. It spits out the instructions and that's what I followed. I'll double check everything again to make sure I didn't miss anything, but I'm pretty sure I have it all correct.

**Comment by Escopy88** [comment]
Yea, can't get it to work. Not sure what's wrong.

**Comment by DIGITALCRIMINAL** [comment]
OF removed "user-id" from the header.
When signing requests, you have to use auth_id=0.

Not doing these will throw an error :/

**Comment by Voldrix** [comment]
Thanks for the tip. Does that only apply if you're not logged in? auth_id=0 would seem to imply that, since User-id and auth_id have the same value when logged in. If I omit user-id, I get the old refresh page error, even if auth_id is there. But it works just fine with user-id and no auth_id. (I'm not doing any authentication/login through the API)

**Comment by DIGITALCRIMINAL** [comment]
For me, if I omit user-id and use 0 instead of my user id(auth_id) when signing requests, I'll be authed in. If I don't, I'll get locked out.

**Comment by Voldrix** [comment]
I added your method for signing as an automatic fallback, so it will try both methods if the first doesn't work. So now it should work for everyone.
