### ISSUE TITLE
Patched?

### ISSUE THREAD

**Issue by mrleduck** [Voldrix/onlyfans-dl-2#30]
I have used multiple dl's before but they all seem to be patched since 2 days you by anychance have a solution getting logged out of my account when trying to download the content then saying access denied in debug console of the dl

**Comment by Voldrix** [comment]
If the script is logging you out, it's most likely because your browser updated. You have to update the browser's user-agent in the script.

**Comment by mrleduck** [comment]
i update it to the latest information and even restarted my browser itself before doing so and it logs me out

**Comment by ItsDepot** [comment]
Also getting this error with an updated session key and updated user agent

**Comment by Voldrix** [comment]
sorry for not getting back to you. Try the latest version, if you still have issues, open a new ticket and I'll try to help.
