### ISSUE TITLE
403

### ISSUE THREAD

**Issue by FlatChoad** [Voldrix/onlyfans-dl-2#34]
Getting a 403 error when using the script. Script logs in and finds the selected users just fine, even creates the directories but won't get any further

**Comment by Voldrix** [comment]
What is the full error message you are getting?

**Comment by FlatChoad** [comment]
`https://cdn2.onlyfans.com/... 403`
With the full url was all it gave me yesterday
Today I got 
'Error getting: https://cdn2.onlyfans.com/.. (skipping)'
then it completed, deleting the directory and trying again it downloaded without error. Storming in the area currently so that's probably just a network issue.
Cookies haven't changed as I've been running a different script since last night.
