### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by stoneforeman** [Voldrix/onlyfans-dl-2#37]
I've tried to read and research my issue, but I'm literally learning Python for this, so bear with me. 

I run this program through terminal. I get this:

import requests
ModuleNotFoundError: No module named 'requests'
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...       6 completed.

[Process completed]

So I installed requests with `pip3 install requests` but I get this:

Versions/3.9/lib/python3.9/site-packages (2.25.1)
Requirement already satisfied: chardet<5,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests) (1.26.6)
Requirement already satisfied: idna<3,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests) (2021.5.30)

To me "requirement already satisfied" sounds like I've installed it. But when I try to run the program again, I get the same error: ModuleNotFoundError: No module named 'requests'

I'm stuck in a loop. What am I doing wrong? (To be honest, I would pay someone to walk me through this, or direct me to a youtube to watch...)

**Comment by razzm8** [comment]
I'm getting this error too, looked for a solution for hours but couldn't find anything, just everyone saying to install the requests module, which I did over and over and still no luck

**Comment by Voldrix** [comment]
issue is with Python, beyond my scope.
