### ISSUE TITLE
Issue after about 80 profiles?

### ISSUE THREAD

**Issue by rubberban** [Voldrix/onlyfans-dl-2#38]
After about 80 profiles that it runs through I get this:

Traceback (most recent call last):
  File "F:\onlyfans.com\onlyfans-dl.py", line 236, in <module>
    get_content("posts", "/users/" + PROFILE_ID + "/posts")
  File "F:\onlyfans.com\onlyfans-dl.py", line 204, in get_content
    download_media(media, MEDIATYPE, album)
  File "F:\onlyfans.com\onlyfans-dl.py", line 146, in download_media
    extension = source.split('?')[0].split('.')
AttributeError: 'NoneType' object has no attribute 'split'

No clue what this means, but it stops running after that.

**Comment by Voldrix** [comment]
I added a check for this null source issue, should work now, gracefully skipping over it.

**Comment by bnsave100** [comment]
> 
> 
> I added a check for this null source issue, should work now, gracefully skipping over it.

I don't want to open new issue so just asking here, if i set to all and run the script it will download in order or expiry or randomly ?

**Comment by Voldrix** [comment]
It will download profiles in the order the API returns them in, not sure what their default sorting method is.
It will download posts in chronological order starting with the oldest first.
