### ISSUE TITLE
Invalid format string error when using the max age functionality

### ISSUE THREAD

**Issue by M4RKOL1V3R** [Voldrix/onlyfans-dl-2#43]
`PS D:\onlyfans-dl-2-master\onlyfans-dl-2-master> python.exe .\onlyfans-dl.py all 30`
`Traceback (most recent call last):
  File "D:\onlyfans-dl-2-master\onlyfans-dl-2-master\onlyfans-dl.py", line 222, in <module>
    MAX_AGE = int((datetime.today() - timedelta(int(PROFILE_LIST.pop(-1)))).strftime("%s"))
ValueError: Invalid format string`

**Comment by Voldrix** [comment]
You must be on Windows. This issue was fixed in July, update to the latest commit.

**Comment by M4RKOL1V3R** [comment]
Ty, works with the latest release. My bad.
