### ISSUE TITLE
Download text as well?

### ISSUE THREAD

**Issue by blmatthews** [Voldrix/onlyfans-dl-2#44]
Has any thought been given to saving the text in posts, messages, etc? I realize the primary purpose is images and videos (for which it works quite nicely!), but some posts have explanatory text, and others are all text (stories, etc.) that it would be nice to save.

Note that I opened the same issue on @k0rnh0li0's version, so if the enhancement is made there, maybe it could be pulled here (or vice versa.)

**Comment by Voldrix** [comment]
I've decided not to implement that feature. Feel free to fork

**Comment by lightninghydra24** [comment]
Please? 🥺
