### ISSUE TITLE
USER_ID auth failed

### ISSUE THREAD

**Issue by LulzRose** [Voldrix/onlyfans-dl-2#49]
Whenever I run the downloader I am receiving this error please help! 

C:\Users\Rose\Downloads\OnlyFans Downloader>python3 onlyfans-dl.py all

itsjustlovely exists.
Downloading new media, skipping pre-existing.
Found 58 posts
Downloaded 0 new posts

USER_ID auth failed, trying without it...
(if this persists you can comment out the USER_ID variable)

ERROR: User not found

C:\Users\Rose\Downloads\OnlyFans Downloader>

**Comment by Dioxadol** [comment]
Yes Im having the exact same problem, and if I comment it as suggested it says the same.

PS C:\users\x\desktop\onlyfans-dl-2-master> python3 .\onlyfans-dl.py dametualma

USER_ID auth failed, trying without it...
(if this persists you can comment out the USER_ID variable)

Downloading content to dametualma
Found 239 posts
Downloaded 0 new posts

ERROR: Access denied.
PS C:\users\x\desktop\onlyfans-dl-2-master>

**Comment by Voldrix** [comment]
You have to update your user-agent when your browser updates.
Now that you've ran the script without it matching, it will automatically log you out of OF. You will have to sign in again and also update your session cookie variable.

**Comment by LulzRose** [comment]
> You have to update your user-agent when your browser updates. Now that you've ran the script without it matching, it will automatically log you out of OF. You will have to sign in again and also update your session cookie variable.

This did not work, updated everything and no change in output

**Comment by Voldrix** [comment]
Make sure your user-agent variable doesn't have any spaces the beginning or end and doesn't start with the word "Browser."
Do you get logged out of OF every time you run the script?

**Comment by LulzRose** [comment]
No spaces or the word browser and I do not get logged out ever

**Comment by LulzRose** [comment]
no sucess in chrome either

**Comment by Voldrix** [comment]
It must be pulling an invalid user somehow. Does the script work for you if you download one user at a time?

**Comment by LulzRose** [comment]
Hmmm this is odd, it appears to work without any issue when doing 1 user at a time

**Comment by Voldrix** [comment]
check your subscriptions list and see if there any accounts listed that are no longer active or shouldn't be there. Try downloading each one and see if any specific profile gives you that error.
If every profile works individually, then it's probably an array error. But I haven't run into this issue before, so I just want check the profiles first before digging in.

**Comment by LulzRose** [comment]
I went through and moved the folders for all of my expired certifications and still am getting the  user auth issue when using "all". Is there an input to get a verbose/debug log?

**Comment by Dioxadol** [comment]
> You have to update your user-agent when your browser updates. Now that you've ran the script without it matching, it will automatically log you out of OF. You will have to sign in again and also update your session cookie variable.

Ok guys i fixed the problem and made it to work. What I did was clear the cache, history, etc. from my browser. Then logged in again into OF and updated the script. The userid was the same, but the sess cookies and the xbc if Im not mistaken changed. Updated with the new values and it worked.

**Comment by Voldrix** [comment]
OF has made another change to the way requests are signed. This may take some time to reverse engineer. This project relies on DIGITALCRIMINAL's signing definitions. So once he figures out the change, I can fix this script.

**Comment by Voldrix** [comment]
I found the issue. They changed the GET parameters for the API requests. I got it fixed in the new commit. Enjoy!
