### ISSUE TITLE
ERROR: Something went wrong. [A74FC255]

### ISSUE THREAD

**Issue by rakuko1** [Voldrix/onlyfans-dl-2#50]
```
>onlyfans-dl.py [redacted] 5

Getting posts newer than 2021-11-29 03:31:57 UTC

USER_ID auth failed, trying without it...
(if this persists you can comment out the USER_ID variable)

ERROR: Something went wrong. [A74FC255]
```

i get this error for each attempt, which causes my browser to log out of OF and the sess id refreshes.

seems that the k0rnh0l0 version also has this problem.

**Comment by Voldrix** [comment]
You have to update your browser user-agent variable when your browser updates or it will log you out like that. Then sign back in and update your session variables.

**Comment by Voldrix** [comment]
Nevermind that, it looks like OF has made a change that disables the script. This will take some reverse engineering, I'll see if I can fix it.

**Comment by waswosi** [comment]
OF constantly keeps me logging out when clicking around in of. It has nothing to do with the tool here. It's a firefox issue.
With Opera I don't get logged out.

**Comment by Voldrix** [comment]
@waswosi I tried to reproduce the error but I don't get logged out. Not even if I try suddenly enabling noscript. Maybe you can open the developer console network tab, and browse around until you get logged out, then look at the last json type request that was made and see if the request headers are different. Especially the signature.
It could also be that your browser cached the old JavaScript file with the old signature algorithm in it, and now that they've changed the signature it's not working right. Try doing a hard refresh (CTRL + SHIFT + R) or (CTRL + F5).

**Comment by Sgt-Nukem** [comment]
> You have to update your browser user-agent variable when your browser updates or it will log you out like that. Then sign back in and update your session variables.

As a tip to prevent this:
I installed the [User-Agent Switcher for Chrome](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg) in my daily use desktop browser and added an entry for OF to the "Permanent Spoof List".
It is also set in the script.

This way a browser update won't invalidate the OF authentication.

The script gets invoked as a scheduled task on my small home server for months now without ever needing to fiddle around in it anymore.

**Comment by Sgt-Nukem** [comment]
> ```
> >onlyfans-dl.py [redacted] 5
> 
> Getting posts newer than 2021-11-29 03:31:57 UTC
> 
> USER_ID auth failed, trying without it...
> (if this persists you can comment out the USER_ID variable)
> 
> ERROR: Something went wrong. [A74FC255]
> ```
> 
> i get this error for each attempt, which causes my browser to log out of OF and the sess id refreshes.
> 
> seems that the k0rnh0l0 version also has this problem.

I get the same since Friday, but my auth is seemingly still okay:
```
$> %PYTHON% ..\onlyfans-dl-2\onlyfans-dl.py all

SUBSCRIPTIONS ERROR: Something went wrong. [A74FC255]
```
As my scheduled task runs every 3 hours (and keeps its logs), I can narrow it down:
Last successful run: [Dec 3rd 2021 @ 11:00 (UTC)](https://www.inyourowntime.zone/2021-12-03_11.00_UTC)
First failed run: [Dec 3rd 2021 @ 14:00 (UTC)](https://www.inyourowntime.zone/2021-12-03_14.00_UTC)

**Comment by waswosi** [comment]
> @waswosi I tried to reproduce the error but I don't get logged out. Not even if I try suddenly enabling noscript. Maybe you can open the developer console network tab, and browse around until you get logged out, then look at the last json type request that was made and see if the request headers are different. Especially the signature. It could also be that your browser cached the old JavaScript file with the old signature algorithm in it, and now that they've changed the signature it's not working right. Try doing a hard refresh (CTRL + SHIFT + R) or (CTRL + F5).

Thank you I've figured it out.
The reason was an old onlyfans download addon in firefox (of xtractor). I've deactivated it and the logging out problem disappeared.

**Comment by rakuko1** [comment]
someone on k0rnh0li0's script added a bit for the app-token which seems to work for them, haven't tried myself. https://github.com/k0rnh0li0/onlyfans-dl/pull/122

kinda odd as this script already uses app-token so idk what the difference would be.

**Comment by Voldrix** [comment]
After having to re-sign back in a hundred times to test each part of the script, I found the piece that fixes it. k0rnh0li0 had to add the app-token header (which we already had), and we had to remove the app-token GET parameter. Enjoy!

**Comment by rakuko1** [comment]
it's working now, had to reset my sess and x-bc as well. thanks Voldrix!
