### ISSUE TITLE
SUBSCRIPTIONS ERROR: Access denied.

### ISSUE THREAD

**Issue by M4RKOL1V3R** [Voldrix/onlyfans-dl-2#52]
Im getting this error when trying to download with parameter 'all' and '1'.
Already cloned new version, and double checked cookies, x-bc and stuff.

**Comment by Voldrix** [comment]
I can't reproduce that error. Please provide more details. What's the exact command you're running? Does it work if you use any other max age? Does it work if you select profiles individually? What version of Python? What OS?

**Comment by sevenwes997** [comment]
Whats is x-bc ? i dont find then

**Comment by blmatthews** [comment]
It's a request header. Look in requests of type xhr in Chrome or json in Firefox. The easiest place to look is probably stats-collect requests, as they're repeated periodically.

**Comment by Voldrix** [comment]
closing due to no response. If you still have an issue, open a new ticket with requested details.
