### ISSUE TITLE
Create a chrome extension where it allows me to see the data I need (JSON)

### ISSUE THREAD

**Issue by LeninZapata** [Voldrix/onlyfans-dl-2#53]
Now that you have taken control of this API, it would not be feasible for you to create a chrome extension where with a single click it shows you these 4 parameters and that allows you to download it with 1 click in JSON format, it is difficult for me to get all this data separately, I'm still confused where to get the headers in chrome and what values to put in headers. Please hope they create an improved solution for this.
```
{
	"user-agent": "",
	"user-id": "",
	"sess": "",
	"x-bc": ""
}
```

**Comment by Voldrix** [comment]
I'm not creating a browser extension. It tells you in the readme how to get those variables. Press F12 to open the developer console.
