### ISSUE TITLE
Downloader can only find 50 posts

### ISSUE THREAD

**Issue by Houkannis** [Voldrix/onlyfans-dl-2#54]
Hi. As the title says. Downloader can only find 50 posts. I have used downloader multiple times and never had this issue before. I tried to download content from multiple OF accounts and the same problem persists.  I even installed olden version of python to see if that would fix the issue but it didint work. Please help

**Comment by Voldrix** [comment]
Looks like OF just changed the API limit from 100 to 50. I changed the limit in the code, it's just a single value on line 72 if you want to just change it in your file instead of re-downloading. Seems to work now.
Let's leave this issue open for a couple days for everyone else to see.

**Comment by Houkannis** [comment]
Yea that did the trick! Thank you!

**Comment by sicr0** [comment]
@Voldrix So to what number should I change that variable to download all content? I put 50 and it didn't change the result

**Comment by lordkitsuna** [comment]
does this mean its not possible to get more than 50 posts from an account? so if an account has like 500 image/videos you can only ever get 50 of them?
