### ISSUE TITLE
error getting

### ISSUE THREAD

**Issue by razzm8** [Voldrix/onlyfans-dl-2#56]
no sure if this a code issue specifically, but on some creators I get an error back every time running the script for the same file, but when copying the link and trying to load the page it doesn't exist basically.
not sure if its something that would be fixed with script or an issue on Of's side

Error getting: https://uk.convert.onlyfans.com/upload/ca5ec809235d2ce4efc583cbf29bbd24336569.MP4 (skipping)

**Comment by Voldrix** [comment]
It's not a bug, it's just a 404. As you said, it doesn't exist, so we can't download it.
