### ISSUE TITLE
posts_limit

### ISSUE THREAD

**Issue by BerserkRaged** [Voldrix/onlyfans-dl-2#6]
Hi, I've installed this and updated the new required information. However, when I try to run it I receive.

```
 File "onlyfans-dl.py", line 83
    if len(list_base) >= posts_limit:
                                    ^
SyntaxError: invalid syntax
```

Anyone else receiving this or can help me fix it?

Thank you.

**Comment by Voldrix** [comment]
Turns out there is a hidden null character in the previous line. Sorry about that it's fixed now

**Comment by BerserkRaged** [comment]
> Turns out there is a hidden null character in the previous line. Sorry about that it's fixed now

Awesome, it's working now. Thank you.
