### ISSUE TITLE
/messages and /stories only gets 1 post

### ISSUE THREAD

**Issue by hanshansenrl** [Voldrix/onlyfans-dl-2#61]
the chats/messages needs an additional id= parameter in api_request apparently corresponding to the last msg read.

stories is probably the same situation

**Comment by Voldrix** [comment]
I updated the pagination for messages from the old offset method to the new ID method. Seems to be working for me now, let me know if you have any issues. I have not updated stories yet, since I don't have any stories in my feed at the moment, so I can't test it. I'll check it when I can.
