### ISSUE TITLE
Limiting downloads between dates

### ISSUE THREAD

**Issue by intelati26** [Voldrix/onlyfans-dl-2#62]
Say, you have the maximum post date. I have read through the code a few times, there's not check to make sure a post isn't "newer" than a date.

My goal is to be able to break up a download into more manageable parts (25GB or so). To do this, I can manually make sure to pull each post. (0 to 50 days, 50 to 100 days. Etc.)

**Comment by intelati26** [comment]
Still leaving this open, but a manual work around.

1. The program downloads the oldest posts first.
2. So, when space runs low, transfer to different location.
3. You are able to either keep the download in progress, or set the "Max age" to skip already downloaded posts.

**Comment by Voldrix** [comment]
I think this is a rather unique requirement. Having to jump between discs for an individual account seems a bit unusual. As such I'm not going to add a newest date limiter, but if you wanted to add it to the code, I'll merge it.
