### ISSUE TITLE
Correct Config - Weird Output

### ISSUE THREAD

**Issue by Kuroo2021** [Voldrix/onlyfans-dl-2#65]
Hello, I follow the information to get the data in to the script but when I run it I get the following.

Usage: C:\Users\...path...\onlyfans-dl-2-master\onlyfans-dl.py <list of profiles / all> [optional: only get last <integer> days of posts]

Make sure to update the session variables at the top of this script (See readme).

Update Browser User Agent (Every time it updates): https://ipchicken.com/

I have double check with IPchicken and the information within the browser the User Agent is correct enter as well as the other data
Same of what I have is below and edited out the information for my stuff of course.

#Session Variables (update every time you login or your browser updates)
USER_ID = "99999999"
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0"
X_BC = "1blah_balah9"
SESS_COOKIE = "5r_COOKIES!__jr"

With all this in mind, I'm not sure what the issue may be. Any input or thoughts? I still a noob at all of this but I'm trying.
Best to you all.

**Comment by Voldrix** [comment]
that is just the normal message you get if you run the script without any input parameters. Just add the profile name you want to scrape after the script name.

**Comment by Voldrix** [comment]
oh, I didn't notice you already closed it. guess you figured out, cool
