### ISSUE TITLE
Non-purchased videos in messages not being downloaded

### ISSUE THREAD

**Issue by bnied** [Voldrix/onlyfans-dl-2#69]
Seconding the issue seen in https://github.com/Voldrix/onlyfans-dl-2/issues/55.

Using the latest script with Python 3.8.

I have two people I'm following where their non-purchased videos are not being downloaded.

Please let me know what other information you need to debug this.

**Comment by projectzero** [comment]
I'm having the same issue with an additional challenge: if the messages directory already existed then the script runs but doesn't download videos in messages. If the messages directory does *not* exist, then I get the error from the screenshot. Manually adding the messages/videos directory doesn't get rid of the error either. 

<img width="841" alt="Screenshot 2022-12-01 at 7 18 44 PM" src="https://user-images.githubusercontent.com/3341925/205207978-a8aeab87-943e-489e-af8c-930c1658a35c.png">

**Comment by Voldrix** [comment]
I switched the messages pagination from ascending to descending order, and that seems to work much better for some reason. Try the new code and let me know.

**Comment by bnied** [comment]
Seems to work well for me, thanks!

I would assume this means that OnlyFans' API may not be handing back a complete list?

**Comment by blmatthews** [comment]
Works for me as well, but man is it slow. I switched the limit to 100 and it still works and is much faster (although I only subscribe to one account, so that's not much of a test).

**Comment by Voldrix** [comment]
I noticed the slowness as well, but it's not the script, OF messages API responds that slowly even on their website.
