### ISSUE TITLE
Stories are not downloaded yet

### ISSUE THREAD

**Issue by Strange-IPmart** [Voldrix/onlyfans-dl-2#71]
Despite the fix for which i thank you, the stories are still not downloaded.

**Comment by Voldrix** [comment]
stories downloaded correctly for every profile I've tested. I can't produce a failure state, so I'll need more information about your issue. enough to reproduce it.
What version of Python, Windows or Linux, does it fail for every single profile, have you double checked you're running the newest code, do you have stories set to true at the top?
line 131 should say
```
if subtype == "stories":
	source = media["files"]["source"]["url"]
```
add to it this
```
if subtype == "stories":
	source = media["files"]["source"]["url"]
	print("source:" + source)
```
see if any of the sources are blank/null or otherwise invalid. or if all the links are good and open in the browser.

**Comment by Strange-IPmart** [comment]
- What version of Python --> Latest 3.11
- Windows or Linux --> Windows 10
- does it fail for every single profile --> Yes
- have you double checked you're running the newest code --> Yes
- do you have stories set to true at the top? --> Yes

- line 131
add to it this

	print("source:" + source) --> I tried adding this line but as soon as
I run the script, the added string is reset.
If I set the script everything to "True", the stories are downloaded
along with everything else as expected.
For my convenience I chose to create subfolders to divide the items
photos, videos, stories, archived etc etc...

If instead I set everything to "False" except the stories, the stories
are not downloaded.
The script finds them but doesn't download them.

"Found 1 stories
Downloaded 0 new stories"

I'm probably doing something wrong or I didn't quite understand how to
use the script correctly but sometimes it happens that I would like to
download only the story photo and not all the profile content.
Maybe it is not possible to use the script for this purpose?Thank you
very much for your interest and help BTW



Il giorno gio 8 dic 2022 alle ore 00:57 Ben Goriesky <
***@***.***> ha scritto:

**Comment by Voldrix** [comment]
so you set photos to false... Then it won't download photos. You can turn posts off, and only download stories, but you need to have photos and/or videos enabled as they apply to every category.

**Comment by Strange-IPmart** [comment]
I have ascertained that in order to download the stories i have to set "True" on both photos and videos.
Thanks for the support.
