### ISSUE TITLE
USER_ID auth failed

### ISSUE THREAD

**Issue by UnknownWitcher** [Voldrix/onlyfans-dl-2#75]
Edit: **Never mind, the error only occurs when I try to get a list of the profiles, but it will download all profiles without an issue.**

Not exactly sure what to do from here. I was using the original and discovered this version so I added all my info to the script but for some reason it keeps giving me the following message.

```
USER_ID auth failed
http 400

Update your browser user-agent variable, then sign back in to OF and update your session variables.
https://ipchicken.com/
```

I tried using chrome as well as firefox, each time I updated the relevant information but I just keep getting auth failed.

**Comment by cpltst2** [comment]
I also get this error, even if i use `all` or an individual profile

**Comment by Voldrix** [comment]
Every time your browser updates, OF logs you out, and you need to update all of the variables, like it says in the error.
if you run the script, and it logs you out on their website, that means your browser user-agent variable no longer matches (your browser updated). don't try to use two browsers. and when you log back in, it also changes your session ID.

look carefully at your variables and make sure there are no extra spaces on either end or extra characters.

**Comment by Voldrix** [comment]
I also just remembered, if you try to download a profile that doesn't exist (typo), or a profile you were subscribed to but has since deleted their account, you'll get that error. Check your active subscriptions for profiles that are disabled. Especially if it only affects "all".

**Comment by biggestsonicfan** [comment]
How does one remove these ghost subscriptions? I've never figured out how...

**Comment by Aithghen** [comment]
I made an edit to my version to get around this issue.  It seems to work so far.  Rename the file from a .txt to a .py and give that a shot.

[onlyfans-dl.txt](https://github.com/Voldrix/onlyfans-dl-2/files/10762238/onlyfans-dl.txt)

**Comment by Aithghen** [comment]
I made some changes to the script that fixed this issue for me.  Rename the file from a .txt to a .py to run it.
[onlyfans-dl.txt](https://github.com/Voldrix/onlyfans-dl-2/files/10762244/onlyfans-dl.txt)

**Comment by biggestsonicfan** [comment]
> I made some changes to the script that fixed this issue for me. Rename the file from a .txt to a .py to run it. [onlyfans-dl.txt](https://github.com/Voldrix/onlyfans-dl-2/files/10762244/onlyfans-dl.txt)

Why not fork and submit a pull request?

**Comment by Houkannis** [comment]
Same issue but this only started as of today. Been using downloader long time and never had this issue before. Updated all the variables as usual, like in the case of new login or update, but doesn't work

**Comment by Voldrix** [comment]
if this only happens when you're getting a list of all profiles, the common culprit is when a user dear their account, it often stays in your subscriptions list, and generates an error when you try to access it. The solution is to go through your subscriptions on the website, and remove any users that have deactivated their account.

**Comment by biggestsonicfan** [comment]
I still fail to see why the downloader has to fail at this error, it's not a fatal error. Is there a particular reason logic-wise once this is encountered it can not move onto the next user?

**Comment by Voldrix** [comment]
I have revised the code to no longer exit on this kind of error, and instead continue on gracefully. I do not have a deactivated account to test against, so let me know if it works for you.
