### ISSUE TITLE
issue with user id and x-bc please help !!

### ISSUE THREAD

**Issue by Mou3az** [Voldrix/onlyfans-dl-2#79]
i am a complete beginner with codes and python and everything i have been struggling for an hour trying to get my user id and x-bc but in my headers requests i can't find it can anyone please help i would give everything !
discord: mouaz#5505

**Comment by rorgoroth** [comment]
At least in Edge do the following:

- Open onlyfans
- Press F12
- Select "Network" tab at the very top of dev tools side-bar
- Press the home button on onlyfans page
- Find in the list "posts?limit=10" and click it
- Scroll down to "Request Headers"

The last 3 items there give you your: user agaent, id and x-bc. Then all you need is to get your sess cookie.
