### ISSUE TITLE
GIF cant be downloaded

### ISSUE THREAD

**Issue by barnyted** [Voldrix/onlyfans-dl-2#81]
a video post sometimes has a gif instead of an mp4 vid, however, the script can't download them.

**Comment by deadbeatdandylyon** [comment]
I know of an account has a .gif but the creator hasn't turned on DRM yet so I can easily download it but If I come across an account that has DRM and a .gif i'll let you know @Voldrix just to help out, and going forward is the best way to get your attention to tag your name?

**Comment by Voldrix** [comment]
if you can download a GIF then this is just the same DRM issue.
sorry, I just don't check github very often.
