### ISSUE TITLE
Verbose mode

### ISSUE THREAD

**Issue by Wolfeman0101** [Voldrix/onlyfans-dl-2#85]
Is there a way to see progress?  Sometimes I'm not sure if it's stuck or just got a ton to download.

**Comment by Voldrix** [comment]
If you set the MAX_AGE flag, it prints every file it downloads, if you want it to also do that when you're downloading an entire profile, just remove the if statement from line 162 (and remove 1 tab indentation from 163).

**Comment by Voldrix** [comment]
I've added a verbosity setting, so now by default it will show every file being downloaded, so as to avoid this confusion.
