### ISSUE TITLE
Error Message when downloading big profile

### ISSUE THREAD

**Issue by waswosi** [Voldrix/onlyfans-dl-2#86]
I get this (of account has 2590 posts):

Traceback (most recent call last):
  File "F:\o.py", line 240, in <module>
    get_content("posts", "/users/" + PROFILE_ID + "/posts")
  File "F:\o.py", line 208, in get_content
    download_media(media, MEDIATYPE, postdate, album)
  File "F:\o.py", line 147, in download_media
    extension = source.split('?')[0].split('.')
AttributeError: 'NoneType' object has no attribute 'split

It's not a general problem, smaller profiles work as it seems.

Please help, it had been working with this of profile too, until now.

**Comment by razzm8** [comment]
seems to be a new feature of some sort onlyfans have implemented to prevent downloads which is on a toggle for the creator. this thread should be updated soon with a way round it

**Comment by Voldrix** [comment]
fix pushed. LMK if you still have issues.

**Comment by Voldrix** [comment]
NVM, DRM still not downloading, but it doesn't crash the script anymore.
