### ISSUE TITLE
No download occurs after executing the script

### ISSUE THREAD

**Issue by SylversVolpe** [Voldrix/onlyfans-dl-2#9]
Now, I am new to messing with Python scripts, so it may well be that I am just missing something very obvious, and if I am, any clarification would be highly appreciated. This is is on windows btw.

I followed the steps throughout, found and inputted all the variables successfully. My steps from there is to open a PowerShell from the folder directory that has the py script in it, and then I'll input "`./onlyfans-dl.py <profile>`". It will then return "`Downloading content to <profile>`", and nothing happens from here. No folders are created, no bandwidth is used, and no errors given.

I looked at some of the other reported issues, and I am not entirely clear on how the download directory works. Is this supposed to download at the root folder I direct the PowerShell to? Am I doing something wrong?

**Comment by karlochacon** [comment]
being downloading like crazy

his is what I use:

cmd or power shell
**./onlyfans-dl.py Secretgirl1**

in the scipt (or course info modified ) I just followed the step by step to get the info needed below use firefox as indicated
**USER_ID = "33xxxxx"
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0"
X_BC = "156e9ea64xxxxxxxxxxxxxxxxxxxxf17eba80b"
SESS_COOKIE = "hivscxxxxxxxxxxxxxxpjicf"**

**Comment by SylversVolpe** [comment]
> 
> 
> being downloading like crazy
> 
> his is what I use:
> 
> cmd or power shell
> **./onlyfans-dl.py Secretgirl1**
> 
> in the scipt (or course info modified ) I just followed the step by step to get the info needed below use firefox as indicated
> **USER_ID = "33xxxxx" USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0" X_BC = "156e9ea64xxxxxxxxxxxxxxxxxxxxf17eba80b" SESS_COOKIE = "hivscxxxxxxxxxxxxxxpjicf"**

I did exactly that afaik, and I get no result. It appears to execute, when it says "Downloading content", but no folders are created, and nothing is downloaded. If I am doing something wrong, I don't see it.

**Comment by Voldrix** [comment]
It may be that you just need to wait a while longer, after you get the downloading content message and before you get the next message, which should be how many posts are found, the script is busy calling the API to get a list of all the posts. The amount of data pulled can get kind of large for profiles with a lot of posts. And it can only pull 100 posts at a time. So once it's collected and concatenated all of that, it will tell you how many are found, then the file structure gets created as needed during the downloading process. For instance, if there are no messages from a profile then that folder won't get made. And yes the directory structure will be built in the current working directory. Try starting with the profile that doesn't have as many posts.

**Comment by Voldrix** [comment]
Yea it's really weird that there is no error message. I can't figure out how to reproduce that, but I have recently added a couple error checks for various other issues that popped up, maybe try it with the latest commit and see if you get anything different.

**Comment by SylversVolpe** [comment]
> 
> 
> It may be that you just need to wait a while longer, after you get the downloading content message and before you get the next message, which should be how many posts are found, the script is busy calling the API to get a list of all the posts. The amount of data pulled can get kind of large for profiles with a lot of posts. And it can only pull 100 posts at a time. So once it's collected and concatenated all of that, it will tell you how many are found, then the file structure gets created as needed during the downloading process. For instance, if there are no messages from a profile then that folder won't get made. And yes the directory structure will be built in the current working directory. Try starting with the profile that doesn't have as many posts.

I waited, a whole day. Tried multiple times since, with no change. The only thing that tells me this even half works for me is that if I hit "all" for the profile, it will list all my subscribed OF profiles as "Downloading content to X, Y, etc". So clearly, it does communicate with my account and the OF API, but something else fails in the middle.

The lack of any error message makes this very hard to troubleshoot though. Not much I can do I suppose.

**Comment by Voldrix** [comment]
So the header signing definitions just changed, and everyone was locked out. The old definitions continue to work for a short time for some people, that's why not everyone noticed at the same time. Digitalcriminal updated those definitions, should be working now. Make sure to download the latest commit though, I've added a couple bug fixes. If you still run into an error, you can open a new issue.
