### ISSUE TITLE
 USER_ID auth failed

### ISSUE THREAD

**Issue by Problematic0K** [Voldrix/onlyfans-dl-2#90]
Since about April I can no longer use the script, every time I try to download a profile I get this error.
"USER_ID auth failed
http 400

Update your browser user-agent variable, then sign back in to OF and update your session variables.
https://ipchicken.com/"

I have tried them all, slogged and relogged, updated the variables countless times, cleared the cache and tried again, but nothing.

What could be the problem?

**Comment by Houkannis** [comment]
Same but this only started as of today. Been using downloader long time never had this issue before. Updated all the variables as usual, like in the case of new login or update, but doesn't work

**Comment by projectzero** [comment]
> Same but this only started as of today. Been using downloader long time and never had this issue before. Updated all the variables as usual, like in the case of new login or update, but doesn't work

Also started today for me.

**Comment by kursku** [comment]
Same here as well

**Comment by MarcoPolansk** [comment]
Same here

**Comment by saspelo** [comment]
also here!

**Comment by Voldrix** [comment]
Fixed. @DIGITALCRIMINALS who provides the digital signing key, made a change. He reverted it, but now we just have to update the url of the file. See 1110ece

https://github.com/DIGITALCRIMINALS/UltimaScraper/issues/1024#issuecomment-1625440345

**Comment by mirrorsssssss** [comment]
> 固定。谁提供了数字签名密钥，进行了更改。他恢复了它，但现在我们只需要更新文件的 url。见[1110ece](https://github.com/Voldrix/onlyfans-dl-2/commit/1110ece2da83e154fb2cb5f8e12052672d3aa647)
> 
> [数字罪犯/终极刮板#1024（评论）](https://github.com/DIGITALCRIMINALS/UltimaScraper/issues/1024#issuecomment-1625440345)
I updated the file, but this issue occurred again
