### ISSUE TITLE
GUI?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [Voldrix/onlyfans-dl-2#91]
Hi

Any plans on creating a GUI for this? For those of us who prefer to just point and click our way through life? lol

Or if anyone knows of one already created?

Thanks!

**Comment by Voldrix** [comment]
I don't really use Python much, and I have zero experience with their graphical libraries. So I won't be making it, but if someone else wants to, I'd be fine adding it to the repo.

**Comment by YouveGotMeowxy** [comment]
how about some other lang, like VB/C#, that just assembles the command line to use as the person chooses options, then simply passes it to the script and runs it?

**Comment by Voldrix** [comment]
I have no interest or time for a GUI. The command line options are so simple I don't see a need for it either. But if you prefer that interface, it sounds like a good learner project.
