### ISSUE TITLE
Long Downloading

### ISSUE THREAD

**Issue by Kubson11** [Voldrix/onlyfans-dl-2#93]
Hi i just trying to download file from profil but im waiting 30 min and i see only this 

![image](https://github.com/Voldrix/onlyfans-dl-2/assets/136191927/207212a5-e32f-479b-996f-079d36a7fc3c)

anyone know what can i do?

**Comment by Voldrix** [comment]
the script doesn't provide updates when you download an entire account, only if the download is date range limited. Look in the folder and see if stuff is actually downloading, it should be.
If you tell it to only download the last N days, it will output the name of everything it downloads. I suppressed that when you download an entire account to avoid spam. You can comment line 167 if you prefer to see every file.

**Comment by Voldrix** [comment]
I have added a verbosity setting to the script. So now by default it will show every file being downloaded, as to avoid this kind of confusion.
