### ISSUE TITLE
HTTP 400 Auth Failed

### ISSUE THREAD

**Issue by GSNotifications** [Voldrix/onlyfans-dl-2#94]
Using the latest version posted with the fixed signature stuff, input the right details (I used the one this is based on for about a year) and every time I try get it to display all profiles it errors out. with 
USER_ID auth failed
http 400

Update your browser user-agent variable, then sign back in to OF and update your session variables.
https://ipchicken.com/ - I've tried on two browsers, edge and Firefox and both produce the same results. I've also tried signing in and out of my account to generate new tokens etc but nothing has worked.

**Comment by Voldrix** [comment]
The only thing I can think of, is when a user deactivates their account, it sometimes stays in your subscriptions list. If you go through your list of following accounts on the site, and remove any of the deactivated accounts, that may fix the issue. I know this has fixed a similar issue in the past.

**Comment by blmatthews** [comment]
Is there any way to detect that in the script? Seems like a useful enhancement if so.

**Comment by Voldrix** [comment]
I have added a fix that prevents the script from exiting on that kind of error. It will continue to the next user gracefully.
