### ISSUE TITLE
Only pictures are downloaded instead videos now

### ISSUE THREAD

**Issue by waswosi** [Voldrix/onlyfans-dl-2#99]
The script downloads only the picture from the video not the video itself from the posts from recent weeks or months. Older posts are downloaded correctly. But script shows now error or something. Can this be repaired?

**Comment by Voldrix** [comment]
this is a placeholder for DRM videos that cannot be downloaded. See https://github.com/Voldrix/onlyfans-dl-2/issues/87#issuecomment-1538907459
